services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/WINSERVER_NICKEL_VNEXTPREVIEW_22509_STANDARD_DATACENTER_EN-US/Windows_InsiderPreview_Server_vNext_en-us_22509.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "1"
      DISK_SIZE: "50G"
      DISK2_SIZE: "35G"
      MANUAL: "Y"
      BOOT_MODE: "windows_plain"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./longhorn:/storage2
      - ./winc:/data
      - ./virt:/oem
    restart: always
    stop_grace_period: 2m
