services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/thelonghornarchive/Windows%20Vista%20build%205365.8%20%28x86%29.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "1"
      DISK_SIZE: "50G"
      DISK_TYPE: "ide"
      MANUAL: "Y"
      BOOT_MODE: "windows_legacy"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./winc:/data
      - ./virt:/oem
    restart: always
    stop_grace_period: 2m
