services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "tiny10"
      RAM_SIZE: "7G"
      CPU_CORES: "1"
      DISK_SIZE: "50G"
      DISK2_SIZE: "35G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./longhorn:/storage
      - ./winc:/data
      - ./virt:/oem
    restart: always
    stop_grace_period: 2m
