services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/windows-developer-preview-64bit-english/WindowsDeveloperPreview64bitEnglish.iso"
      RAM_SIZE: "8G" 
      CPU_CORES: "1"
      DISK_SIZE: "50G"
      DISK_TYPE: "ide"
      MANUAL: "Y"      
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./winc:/data
    restart: always
    stop_grace_period: 2m
